/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

public enum gdAffineStandardMatrix {
  GD_AFFINE_TRANSLATE = 0,
  GD_AFFINE_SCALE,
  GD_AFFINE_ROTATE,
  GD_AFFINE_SHEAR_HORIZONTAL,
  GD_AFFINE_SHEAR_VERTICAL
}

}
