/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

public enum gdCropMode {
  GD_CROP_DEFAULT = 0,
  GD_CROP_TRANSPARENT,
  GD_CROP_BLACK,
  GD_CROP_WHITE,
  GD_CROP_SIDES,
  GD_CROP_THRESHOLD
}

}
