/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

using System;
using System.Runtime.InteropServices;

public class gdFTStringExtra : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal gdFTStringExtra(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(gdFTStringExtra obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~gdFTStringExtra() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libgdPINVOKE.delete_gdFTStringExtra(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int flags {
    set {
      libgdPINVOKE.gdFTStringExtra_flags_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdFTStringExtra_flags_get(swigCPtr);
      return ret;
    } 
  }

  public double linespacing {
    set {
      libgdPINVOKE.gdFTStringExtra_linespacing_set(swigCPtr, value);
    } 
    get {
      double ret = libgdPINVOKE.gdFTStringExtra_linespacing_get(swigCPtr);
      return ret;
    } 
  }

  public int charmap {
    set {
      libgdPINVOKE.gdFTStringExtra_charmap_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdFTStringExtra_charmap_get(swigCPtr);
      return ret;
    } 
  }

  public int hdpi {
    set {
      libgdPINVOKE.gdFTStringExtra_hdpi_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdFTStringExtra_hdpi_get(swigCPtr);
      return ret;
    } 
  }

  public int vdpi {
    set {
      libgdPINVOKE.gdFTStringExtra_vdpi_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdFTStringExtra_vdpi_get(swigCPtr);
      return ret;
    } 
  }

  public string xshow {
    set {
      libgdPINVOKE.gdFTStringExtra_xshow_set(swigCPtr, value);
    } 
    get {
      string ret = libgdPINVOKE.gdFTStringExtra_xshow_get(swigCPtr);
      return ret;
    } 
  }

  public string fontpath {
    set {
      libgdPINVOKE.gdFTStringExtra_fontpath_set(swigCPtr, value);
    } 
    get {
      string ret = libgdPINVOKE.gdFTStringExtra_fontpath_get(swigCPtr);
      return ret;
    } 
  }

  public gdFTStringExtra() : this(libgdPINVOKE.new_gdFTStringExtra(), true) {
  }

}

}
