/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

public enum gdInterpolationMethod {
  GD_DEFAULT = 0,
  GD_BELL,
  GD_BESSEL,
  GD_BILINEAR_FIXED,
  GD_BICUBIC,
  GD_BICUBIC_FIXED,
  GD_BLACKMAN,
  GD_BOX,
  GD_BSPLINE,
  GD_CATMULLROM,
  GD_GAUSSIAN,
  GD_GENERALIZED_CUBIC,
  GD_HERMITE,
  GD_HAMMING,
  GD_HANNING,
  GD_MITCHELL,
  GD_NEAREST_NEIGHBOUR,
  GD_POWER,
  GD_QUADRATIC,
  GD_SINC,
  GD_TRIANGLE,
  GD_WEIGHTED4,
  GD_METHOD_COUNT = 21
}

}
