/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

public enum gdPaletteQuantizationMethod {
  GD_QUANT_DEFAULT = 0,
  GD_QUANT_JQUANT = 1,
  GD_QUANT_NEUQUANT = 2,
  GD_QUANT_LIQ = 3
}

}
