/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

using System;
using System.Runtime.InteropServices;

public class gdPoint : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal gdPoint(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(gdPoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~gdPoint() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libgdPINVOKE.delete_gdPoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      libgdPINVOKE.gdPoint_x_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdPoint_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      libgdPINVOKE.gdPoint_y_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdPoint_y_get(swigCPtr);
      return ret;
    } 
  }

  public gdPoint() : this(libgdPINVOKE.new_gdPoint(), true) {
  }

}

}
