/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

using System;
using System.Runtime.InteropServices;

public class gdPointF : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal gdPointF(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(gdPointF obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~gdPointF() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libgdPINVOKE.delete_gdPointF(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double x {
    set {
      libgdPINVOKE.gdPointF_x_set(swigCPtr, value);
    } 
    get {
      double ret = libgdPINVOKE.gdPointF_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      libgdPINVOKE.gdPointF_y_set(swigCPtr, value);
    } 
    get {
      double ret = libgdPINVOKE.gdPointF_y_get(swigCPtr);
      return ret;
    } 
  }

  public gdPointF() : this(libgdPINVOKE.new_gdPointF(), true) {
  }

}

}
