/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Imazen.LibGD.Native {

using System;
using System.Runtime.InteropServices;

public class gdRect : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal gdRect(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(gdRect obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~gdRect() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libgdPINVOKE.delete_gdRect(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      libgdPINVOKE.gdRect_x_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdRect_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      libgdPINVOKE.gdRect_y_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdRect_y_get(swigCPtr);
      return ret;
    } 
  }

  public int width {
    set {
      libgdPINVOKE.gdRect_width_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdRect_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      libgdPINVOKE.gdRect_height_set(swigCPtr, value);
    } 
    get {
      int ret = libgdPINVOKE.gdRect_height_get(swigCPtr);
      return ret;
    } 
  }

  public gdRect() : this(libgdPINVOKE.new_gdRect(), true) {
  }

}

}
